modmap:
  - name: Global
    remap:
      CapsLock: Ctrl_L
  - name: macOS
    remap:
      KEY_LEFTMETA: KEY_LEFTALT
      KEY_LEFTALT: KEY_LEFTMETA
    device:
        only: ["Apple MTP keyboard"]
  - name: REALFORCE
    remap:
      KEY_GRAVE: KEY_ESC
    device:
        only: ["Topre REALFORCE 87 US"]


keymap:
  - name: Global
    remap:
      Shift_L-Esc: KEY_GRAVE
      Shift_R-Esc: Shift-KEY_GRAVE
      Shift_R-backspace: KEY_DELETE
  - name: Firefox Emacs Binding
    application:
      only: [firefox, zen, Google-chrome]
    remap:
      C-Shift-p: C-Shift-p
      C-Shift-n: C-Shift-n
      C-M-p: C-p
      C-p: up
      C-n: down
      C-s: C-f
      C-M-S: C-s
